# These are supported funding model platforms

github: [dragonrun1]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: dragonrun1
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: dragonrun1
issuehunt: dragonrun1
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
