[package]
name = "rust_rpi_4wd_car"
version = "0.0.3"
authors = ["Michael Cummings <dragonrun1@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0.40"
ctrlc = { version ="3.1.8", features = ["termination"] }
rppal = {git = "https://github.com/golemparts/rppal", features = ["hal", "hal-unproven"]}
thiserror = "1.0.24"
